name: betterdoc-development-blog
version: 0.1.0
url: https://github.com/hannes-steffenhagen-betterdoc/betterdoc-development-blog

executables:
  gensite:
    main: site.hs
    source-dirs: generator
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >=4.9 && < 5
